<?php
/**
 * Created by PhpStorm.
 * User: paulv
 * Date: 2018/4/6
 * Time: 21:59
 */

namespace backend\controllers;


use yii\web\Controller;
use Yii;

class BaseController extends Controller
{

     public  $admin_id;
     public  $request;
     public  function init()
     {

         parent::init(); // TODO: Change the autogenerated stub
     }


     public  function beforeAction($action)
     {
         //不需要权限验证的控制器
         $skipController = [
             'site/error',
             'site/index',
             'site/login',
             'site/logout',
             'site/captcha'
         ];
         //获取controller_id和action_id
         $controller_id = Yii::$app->controller->id;
         $action_id     = Yii::$app->controller->action->id;
         //判断用户是否登陆如果没有登陆跳转到登录页
         if (Yii::$app->user->isGuest && (!in_array($action_id, ['login','error']) ) ) {
             return  $this->redirect(['site/login']);
         }
         //如果用户已登录则跳转到首页
         if (!Yii::$app->user->isGuest && ($action_id =='login')) {
             return $this->redirect(['site/index']);
         }
         return parent::beforeAction($action);
     }


     public  function getRequest(){

        $this->request = Yii::$app->request;

     }


}