<?php
/**
 * Created by PhpStorm.
 * User: admin
 * Date: 2018/8/16
 * Time: 14:50
 */

namespace frontend\controllers;



use common\models\mongo\BaseFrontendMongo;
use Yii;
use yii\web\Controller;
use yii\web\Response;

class BaseController extends Controller
{
    protected  $result = ['code'=>0,'msg'=>'','data'=>''];
    public     $enableCsrfValidation = false;

    public  function  init()
    {
        //未登录
        if(Yii::$app->user->isGuest){

        }
        parent::init(); // TODO: Change the autogenerated stub
        Yii::$app->response->format = Response::FORMAT_JSON;
    }

    public function  beforeAction($action)
    {
        //获取当前访问控制器的方法和控制器名称
        //$action->actionMethod 方法名称
        //$action->controller 控制器名称
        BaseFrontendMongo::$log = new BaseFrontendMongo($action);
         if(!empty(BaseFrontendMongo::$log)){
             BaseFrontendMongo::$log->initMongo($action);
         }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public  function afterAction($action, $result)
    {
        if (!empty(BaseFrontendMongo::$log)){
            BaseFrontendMongo::$log->end($result);
        }
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }


}