<?php
/**
 * Created by PhpStorm.
 * User: paulversion
 * Date: 2018/8/16
 * Time: 14:31
 */
namespace common\models\mongo;


class BaseFrontendMongo extends BaseMongo
{
    //集合名称
    public  static $collection_name = 'default';
    //mongo数据库名称
    public  static $db_name         = 'develop';

    public function __construct($action)
    {
        if(!isset($action->controller) || !isset($action->actionMethod)){
            return false;
        }
        //get_class 获取对象的类名称
        $class_name  = get_class($action->controller);
        //将类名转换为下划线类型
        self::$collection_name = strtolower(trim(preg_replace('/\\\\/','_',$class_name)));

    }

    /**
     * 开始记录日志
     * @param string $action_name
     * @param string $title
     */
    public  function begin($action_name = '', $title = '')
    {
        parent::begin($action_name, $title); // TODO: Change the autogenerated stub
    }

    /**
     * 日志记录结束
     * @param string $result
     * @return bool
     */
    public function end($result = '')
    {
        return parent::end($result); // TODO: Change the autogenerated stub
    }


    /**
     * 给记录添加属性
     * @param $field_name
     * @param $value
     * @return bool
     */
    public  function  addLogField($field_name, $value)
    {
        return parent::addLogField($field_name, $value); // TODO: Change the autogenerated stub
    }


    /**
     * 添加日志
     * @param 日志标题 $title
     * @param string $log_data
     * @return bool
     */
    public  function  addLogDetail($title, $log_data = '')
    {
        $data = [];
        //增加调试信息
        $trc = debug_backtrace();
        if(isset($trc[0])&&isset($trc[0]['file']) && isset($trc[0]['line'])){
            $data['title'] = "[{$title}] [".date("Y-m-d H:i:s")."] [{$trc[0]['file']}] [{$trc[0]['line']}]";
        }
        if (is_array($log_data)){
            $data = array_merge($data,$log_data);
        }else{

            $data[]  = $log_data;
        }
        return parent::addLogDetail($title, $data); // TODO: Change the autogenerated stub
    }

}